// quiz/quiz.engine.js
// FINAL CLEAN VERSION (AI generator only)

const OpenAI = require("openai");
const prompts = require("./quiz.prompts");
const validateQuiz = require("./quiz.validator");

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const MIN_QUESTIONS = 25;
const MAX_QUESTIONS = 30;


// ===============================
// Helpers
// ===============================
function normalizeText(str) {
  return String(str || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ");
}

function extractJson(raw) {
  if (!raw) throw new Error("Empty AI response");

  const cleaned = raw.replace(/```json|```/gi, "").trim();
  const start = cleaned.indexOf("[");
  const end = cleaned.lastIndexOf("]");

  if (start === -1 || end === -1) {
    throw new Error("No JSON array found");
  }

  return JSON.parse(cleaned.slice(start, end + 1));
}


// ===============================
// Normalize AI output
// ===============================
function normalizeQuiz(aiData) {
  if (!Array.isArray(aiData)) {
    throw new Error("AI output is not an array");
  }

  const normalized = [];

  for (const q of aiData) {
    if (!q.question || !Array.isArray(q.options) || q.options.length !== 4) {
      continue;
    }

    let correctIndex = -1;

    if (
      typeof q.correctIndex === "number" &&
      q.correctIndex >= 0 &&
      q.correctIndex <= 3
    ) {
      correctIndex = q.correctIndex;
    }

    if (correctIndex === -1 && q.answer) {
      const ans = normalizeText(q.answer);
      correctIndex = q.options.findIndex(
        (opt) => normalizeText(opt) === ans
      );
    }

    if (correctIndex === -1) continue;

    normalized.push({
      question: q.question.trim(),
      options: q.options.map((o) => o.trim()),
      correctIndex,
      difficulty: ["easy", "medium", "hard"].includes(q.difficulty)
        ? q.difficulty
        : "medium",
    });
  }

  if (normalized.length < MIN_QUESTIONS) {
    throw new Error(
      `No valid questions generated by AI (got ${normalized.length})`
    );
  }

  return normalized.slice(0, MAX_QUESTIONS);
}


// ===============================
// Call OpenAI
// ===============================
async function callAI(prompt) {
  const res = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [{ role: "user", content: prompt }],
    temperature: 0.6,
  });

  return res.choices?.[0]?.message?.content;
}


// ===============================
// Generate quiz (admin only)
// ===============================
async function generateQuiz({ topic, language }) {
  let prompt;

  switch (topic) {
    case "quantitative":
      prompt = prompts.quantitativePrompt();
      break;
    case "reasoning":
      prompt = prompts.reasoningPrompt();
      break;
    case "gk":
      prompt = prompts.gkPrompt();
      break;
    case "current_affairs":
      prompt = prompts.currentAffairsPrompt();
      break;
    case "programming":
      if (!language) throw new Error("Programming language required");
      prompt = prompts.programmingPrompt(language);
      break;
    default:
      throw new Error("Invalid quiz topic");
  }

  const raw = await callAI(prompt);

  const parsed = extractJson(raw);
  const quiz = normalizeQuiz(parsed);

  validateQuiz(quiz);

  return quiz;
}

module.exports = generateQuiz;
